name: Test Workflow

on: push



jobs:
  tests:
    runs-on: ubuntu-latest
 
  services:
   image: MySQL
   env:
   - MySQL_USER: kaddour
   - MySQL_PASSWORD: boubou
   - MySQL_BD: MySQL
   ports:
   - 5432:5432
   options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
  
  steps:
   - uses: actions/checkout@v1
   - name: Set up Python 3.5.7
     uses: actions/setup-python@v1
     with:
      python-version: 3.5.7
    - name: Install dependencies
     run: pip install -r requirements.txt
    - name: Run tests
      run: python manage.py test
