name: Test Workflow
on: push
env:
  - MySQL_USER: root
  - MySQL_PASSWORD: root
  - MySQL_HOST: localhost
jobs:
  tests:
    runs-on: ubuntu-latest
    services:
     image: mysql:5.7
     port:
      - 3307:3307
   
    steps:
    - name: Run tests
      run: python manage.py test
