name: Test Workflow

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
 
  services:
   image: MySQL
   env:
   - MySQL_USER: kaddour
   - MySQL_PASSWORD: boubou
   - MySQL_BD: MySQL
   ports:
   - 5432:5432
   options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
  
  steps:
  - name: Run tests
    run: python manage.py test
