name: Test Workflow

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
 
    services:
     image: mysql:5.7
     env:
      - MySQL_USER: root
      - MySQL_PASSWORD: root
      - MySQL_HOST: localhost
     port:
      - 3307:3307
     options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
  
    steps:
    - name: Run tests
      run: python manage.py test
